### ISSUE TITLE
Create Prefab menu for the SenseiX plugin User-Management

### ISSUE THREAD

**Issue by dcompton** [senseix/senseix_unity_plugin#6]
Lets create a prefab that bundles together the following:
ACOUNT SIGN-IN
1. The plug-in will use the unique identifier as per provided by unity and prompt the user or have a button that allows the user to tie a specific game with an application. 
2. Upon pushing the button to register a game, the device will generate a verification code.  On the press of a button, a preferred browser will be opened, over https, with a json field communicating the verification code.   Alternatively, the user can navigate to the website on any device manually and enter the verification code.
3. The webpage parent.senseix.com/device_management will require the user to enter their user name and password (if session information is not pre-cached in the browser) with a highlighted option to register the application/device pair (we can add a COPA privacy policy on the page as well).
4. Upon opening up the game again the unique Id will be sent as part of the device registration request - at this point we will return a unique auth_token for that application/device pair.

GOTCHA's
1. what happens if I sell the device? 
   -I should be resetting to factory default
   -what happens if someone spoofs my unique ID? 
     -well...only on App will be compromised. 
   -others?

2. Merge data: 
   In the event that a student has answered problems in a game that is not tied to an account upon signing in the parent is prompted to either:
   a. Merge the collected problems with an existing account
   b. create a new profile for the collected problems (just enter a pupils name).
   c. throw away all collected data. 

3. The ability to switch between player profiles - each account can have a number of profiles associated with it. In most cases these should 

4. Sign-out an account. This will have the effect of going back to a temporary account for that device and effectively deleting the auth_token and device/pair - its really more of a de-registration process.

**Comment by milkshakeiii** [comment]
Things are pretty well figured out with this menu now.
